FROM centos:7
MAINTAINER sunwenju
RUN yum install -y gcc wget gcc-c++ make \
    openssl-devel pcre-devel gd-devel \
    iproute net-tools telnet wget curl unzip perl kernel-headers kernel-devel vim && \
    yum clean all && \
    rm -rf /var/cache/yum/*
RUN yum -y install gcc make pcre pcre-devel zlib zlib-devel openssl-devel  readline-devel && \
    cd && \
    wget https://openresty.org/download/openresty-1.15.8.1.tar.gz  && \
    tar zxf openresty-1.15.8.1.tar.gz && \
    cd openresty-1.15.8.1 && \
    ./configure --prefix=/usr/local/openresty \
    --with-http_stub_status_module \
    --with-http_ssl_module \
    --with-stream	&& \
    make -j 2 && make install && \
	ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
	cd && \
	wget https://github.com/unixhot/waf/archive/v1.0.0.tar.gz && \
	tar zxf v1.0.0.tar.gz && \
	cp -r waf-1.0.0/waf /usr/local/openresty/nginx/conf/ && \
        mkdir -p /usr/local/openresty/nginx/conf/{vhosts,ssl} && \
        mkdir -p /usr/local/openresty/nginx/downloads && \
		groupadd nginx && \
		useradd -g nginx -s /sbin/nologin nginx  
ENV PATH $PATH:/usr/local/openresty/nginx/sbin
COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY osce.conf /usr/local/openresty/nginx/conf/vhosts/osce.conf
COPY ssl/bbs.sunwenju.com.pem  /usr/local/openresty/nginx/conf/ssl/
COPY ssl/bbs.sunwenju.com-key.pem  /usr/local/openresty/nginx/conf/ssl/

RUN yum install -y gcc wget gcc-c++ make kernel-devel kernel-headers \
    openssl-devel pcre-devel gd-devel \
    iproute net-tools telnet wget curl unzip perl kernel-headers kernel-devel vim && \
    yum clean all && \
    rm -rf /var/cache/yum/* && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN cd /root && \
 wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u141-b15/336fa29ff2bb4ef291e347e091f7f4a7/jdk-8u141-linux-x64.tar.gz" && \
 tar zxf jdk-8u141-linux-x64.tar.gz  && \
 mv jdk1.8.0_141  /usr/local/jdk1.8
RUN cd /root && \
  wget https://mirrors.tuna.tsinghua.edu.cn/apache/zookeeper/zookeeper-3.4.14/zookeeper-3.4.14.tar.gz && \
  tar zxf zookeeper-3.4.14.tar.gz && \
  mv  zookeeper-3.4.14  /usr/local/zookeeper && \
  mv /usr/local/zookeeper/conf/zoo_sample.cfg /usr/local/zookeeper/conf/zoo.cfg

RUN cd /root && \
  wget http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.31/bin/apache-tomcat-8.5.31.tar.gz && \
  tar zxf apache-tomcat-8.5.31.tar.gz && \
  mv  apache-tomcat-8.5.31 /usr/local/tomcat && \
  rm -rf /root/* 

ENV JAVA_HOME=/usr/local/jdk1.8
ENV JRE_HOME=$JAVA_HOME/jre
ENV CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib:$CLASSPATH
ENV PATH=/sbin:$JAVA_HOME/bin:$PATH

COPY run.sh /tmp/run.sh
RUN chmod +x /tmp/run.sh
EXPOSE 80 443 2181 8080
CMD ["/tmp/run.sh"]

