version: '3'
services:
  nginx_tomcat:
    container_name: nginx_tomcat
    image: registry.cn-shenzhen.aliyuncs.com/wenjusir/aju:nginx_tomcat
    #build:
      #context: ./nginx_tomcat
      #dockerfile: Dockerfile_nginx_tomcat
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - lnmt
    volumes:
      - ./nginx_tomcat/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx_tomcat/osce.conf:/usr/local/openresty/nginx/conf/vhosts/osce.conf
      - ./nginx_tomcat/ssl:/usr/local/openresty/nginx/conf/ssl
      - ./webapps:/usr/local/tomcat/webapps
      - ./webapps:/usr/local/openresty/nginx/html

  mysql:
    container_name: mysql5.7
    image: mysql:5.7
    ports:
      - 3306:3306
    networks:
      - lnmt
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    command: --character-set-server=utf8
    environment:
      MYSQL_ROOT_PASSWORD: 123456@
    
  
  redis:
    container_name: redis
    image: registry.cn-shenzhen.aliyuncs.com/wenjusir/aju:redis
    #build:
      #context: ./nginx_tomcat
      #dockerfile: Dockerfile_redis
    ports:
      - 6379:6379
    
    networks:
      - lnmt
    volumes:
      - ./redis:/data
      - ./redis/conf:/usr/local/etc/redis
    command: redis-server --port 6379 --requirepass 123456@ --appendonly yes

networks:
  lnmt:
