version: '3'
services:
  nginx:
    container_name: nginx
    image: registry.cn-shenzhen.aliyuncs.com/wenjusir/aju:nginx
    #build:
      #context: ./nginx_tomcat
      #dockerfile: Dockerfile_nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - lnmt
    volumes:
      - ./nginx_tomcat/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx_tomcat/osce.conf:/usr/local/openresty/nginx/conf/vhosts/osce.conf
      - ./nginx_tomcat/ssl:/usr/local/openresty/nginx/conf/ssl
      - ./webapps:/usr/local/openresty/nginx/html

  tomcat:
    container_name: nginx
    image: registry.cn-shenzhen.aliyuncs.com/wenjusir/aju:tomcat
    #build:
      #context: ./nginx_tomcat
      #dockerfile: Dockerfile_tomcat
    ports:
      - 8080:8080
      - 8989:8989
    networks:
      - lnmt
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
      

  mysql:
    container_name: mysql5.7
    image: mysql:5.7
    ports:
      - 3306:3306
    networks:
      - lnmt
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    command: --character-set-server=utf8
    environment:
      MYSQL_ROOT_PASSWORD: 123456@
      #MYSQL_DATABASE: test 
      #MYSQL_USER: user
      #MYSQL_PASSWORD: user123456
    
  
  redis:
    container_name: redis
    image: registry.cn-shenzhen.aliyuncs.com/wenjusir/aju:redis
    #build:
      #context: ./nginx_tomcat
      #dockerfile: Dockerfile_redis
    ports:
      - 6379:6379
    
    networks:
      - lnmt
    volumes:
      - ./redis:/data
      - ./redis/conf:/usr/local/etc/redis
    command: redis-server --port 6379 --requirepass 123456@ --appendonly yes

  zookeeper:
    container_name: zookeeper
    image: registry.cn-shenzhen.aliyuncs.com/wenjusir/aju:zookeeper
    ports:
      - 2181:2181
      - 2182:2182
    networks:
      - lnmt

  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - 11211:11211
    networks:
      - lnmt
networks:
  lnmt:
